logging:
  level:
    root: warn
    com.rest.api: info
  path: /home/ec2-user/app/log
  file:
    max-history: 7

spring:
  profiles: alpha
  datasource:
    url: jdbc:mysql://localhost:3306/daddyprogrammer?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: positive2
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: none
      format_sql: true
    showSql: true
    generate-ddl: false
  url:
    base: http://dev-api.daddyprogrammer.org
  redis:
    host: localhost
    port: 6379